### ISSUE TITLE
Invariant Violation: Your JavaScript code tried to access a native module that doesn't exist

### ISSUE THREAD

**Issue by amrelwany** [allboatsrise/expo-gigya#1]
I have installed the packages 
yarn add @allboatsrise/expo-gigya
yarn add @sap_oss/gigya-react-native-plugin-for-sap-customer-data-cloud@0.2.2 

And added the following to app.json
 "plugins": [
      [
        "@allboatsrise/expo-gigya",
        {
          "gigyaSwiftSdkVersion": "1.5.0"
        }
      ]
    ] 
When I added the following,
import { Gigya} from '@allboatsrise/expo-gigya';
-----
Gigya.initFor("XXXXXX");

The following Error occured:
Invariant Violation: Your JavaScript code tried to access a native module that doesn't exist. 

If you're trying to use a module that is not supported in Expo Go, you need to create a development build of your app. See https://docs.expo.dev/development/introduction/ for more info., js engine: hermes
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:102:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:148:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:39 in handleError
at node_modules/expo/build/errors/ExpoErrorManager.js:25:19 in errorHandler
at node_modules/expo/build/errors/ExpoErrorManager.js:30:24 in <anonymous>
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-config/node_modules/metro-runtime/src/polyfills/require.js:237:40 in guardedLoadModule
at node_modules/metro-config/node_modules/metro-runtime/src/polyfills/require.js:131:23 in metroRequire
at http://192.168.1.6:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:null in global

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:102:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:148:19 in handleException
- ... 7 more stack frames from framework internals
<img width="342" alt="Screenshot 2023-06-16 at 12 39 10 AM" src="https://github.com/allboatsrise/expo-gigya/assets/9930308/07b38619-fcaf-470f-b006-9ea88c6e63a4">

**Comment by xsgurdag** [comment]
Did you find any solution? How did you implement gigya to your expo app? @amrelwany

**Comment by andrejpavlovic** [comment]
Released version `50.0.0` for expo SDK 50. Please open a separate issue if you're still having issues.
